### ISSUE TITLE
load_clean_eod_data

### ISSUE THREAD

**Issue by gilbaes** [asa-github/asaBacktesting#5]
I tried to use load_clean_eod_data as follows:

```r
price_by_sector <- lapply(sector_list, load_clean_eod_data, "market_eod", ref_data$security_id, "2010-01-01", "2012-12-31")
```

I got the error:

 Loading eod_data from BBG000QLTZ50.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG00178PGX3.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG001R34D26.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG003G4DHL2.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG005BHWJL8.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG0065YWM39.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG006K4WHV8.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG006MJ3Y48.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG0073DKJP1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG0086LKMG1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
 Loading eod_data from BBG009R3Q7R1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
	loading data from the database
 Show Traceback
 
 Rerun with Debug
 Error in .pkgenv$mongos[[db]] : no such index at level 1

**Comment by eriknil** [comment]
Wrong arguments. Seems to use security-Id as database and market_eod as collection

Sent from my iPhone

On 7 mars 2016, at 10:02, gilbaes <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to use load_clean_eod_data as follows:

price_by_sector <- lapply(sector_list, load_clean_eod_data, "market_eod", ref_data$security_id, "2010-01-01", "2012-12-31")

I got the error:

Loading eod_data from BBG000QLTZ50.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG00178PGX3.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG001R34D26.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG003G4DHL2.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG005BHWJL8.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG0065YWM39.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG006K4WHV8.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG006MJ3Y48.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG0073DKJP1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG0086LKMG1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
Loading eod_data from BBG009R3Q7R1.market_eod for 1138 security ids from 2010-01-01to 2012-12-31
loading data from the database
Show Traceback

Rerun with Debug
Error in .pkgenv$mongos[[db]] : no such index at level 1

-
